### ISSUE TITLE
Research best CI/CD platforms

### ISSUE THREAD

**Issue by reginawang3495** [cs130-w21/13#21]
## User Story
As a **Software Engineer**, I would like **like to know which CI/CD platform is best** so that **it will be easy to maintain and free to host the server**.

## Detailed Description
Research the different continuous deployment tools: Heroku/Travis/Git Actions. Find one that is easy to setup and maintain, and is free to host the backend.

## Acceptance Criteria
- [ ] Given **[I want to setup CI/CD pipeline]**, then **[I know which tool is easiest and free for the backend]**

**Comment by ghuser1023** [comment]
Merged into #17 and #10.
