### ISSUE TITLE
Command Blocks - Tooltips

### ISSUE THREAD

**Issue by ashen-00** [cs130-w21/13#33]
## User Story
As a **player**, I would like **have tooltips for the command blocks** so that **I have an easy way of remembering what a command does**.

## Detailed Description
Command blocks should provide additional information to the player on hover so that they can be reminded of what individual commands does. 

## Acceptance Criteria
- [ ] Given **a player hovers their cursor over a command for X time**, then **a tooltip should appear over the command**
- [ ] Given **a player removes their cursor from the command**, then **the tooltip should no longer appear over the command**

**Comment by Soheilvt75** [comment]
The project was changed and this story is no loner needed.
