### ISSUE TITLE
Start up a backend 

### ISSUE THREAD

**Issue by reginawang3495** [cs130-w21/13#5]
## User Story
As a **player**, I would like **the client to connect to a backend** so that **I can play the game online**.

## Detailed Description
Startup a backend in Node.js with basic functionality and fill in README.md with basic commands so that it's easy for other software engineers to work on the backend as well.

## Acceptance Criteria
- [ ] Given **you run the command to start a server**, then **the server runs**
- [ ] Given **server is started**, then **you can make a request to the the server successfully**

**Comment by ghuser1023** [comment]
Merged with #7.
